version: "2.0"

services:
  app:
      container_name: app
      build:
        dockerfile: ./Dockerfile
        context: ./app
      ports:
        - "5000:5000"


  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - app
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana-ui:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus